<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- XML comments are shown in Swagger. -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IncidentMonitoring.Core\IncidentMonitoring.Core.csproj" />
    <ProjectReference Include="..\IncidentMonitoring.Infrastructure\IncidentMonitoring.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
